# name: Rust

# on:
#   push:
#     branches: [ "main" ]
#     paths-ignore:
#     - 'LICENSE'
#     - 'README.md'
#   pull_request:
#     branches: [ "main" ]
#     paths-ignore:
#     - 'LICENSE'
#     - 'README.md'

# env:
#   CARGO_TERM_COLOR: always

# jobs:
#   build_and_test:
#     name: Build and test
#     strategy:
#       matrix:
#         os:
#           - ubuntu-latest
#           - macos-latest
#           - windows-latest
#     runs-on: ${{ matrix.os }}

#     steps:
#     - run: git config --global core.autocrlf false

#     - name: "Checkout repository"
#       uses: actions/checkout@v4
    
#     - name: Build
#       run: cargo build --verbose
    
#     - name: Run tests
#       run: cargo test --verbose

#     - name: Check code formatting
#       run: |
#         rustup component add rustfmt
#         cargo fmt --all -- --check